name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: jenkins/inbound-agent:4.13-1

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file jenkins-jnlp-slave/Dockerfile --tag jenkins-jnlp-slave:$(date +%s)
